mysite/myownsite/urls.py
from django.urls import path
from .views import SignUpView
from . import views
urlpatterns = [
    path("", views.home, name="home"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("coment/new", views.comm_new, name="comm_new"),
    path("kabinet/<int:pk>/", views.kab_detail, name="kab_detail")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', include("myownsite.urls")),
    path('admin/', admin.site.urls),
    path("accounts/", include("myownsite.urls")),
    path("accounts/", include("django.contrib.auth.urls"))
]

mysite/myownsite/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser


class Users(AbstractUser):
    pass
    YEAR_IN_SCHOOL_CHOICES = [
        ('7', '7 класс'),
        ('8', '8 класс'),
        ('9', '9 класс'),
        ('10', '10 класс'),
        ('11', '11 класс'),
    ]
    grade = models.CharField(
        max_length=2,
        choices=YEAR_IN_SCHOOL_CHOICES,
        default='7',
    )

    def __str__(self):
        return self.username


class Kabinet(models.Model):
    SUBJECT = [
        ('math', 'Математика'),
        ('phys', 'Физика'),
        ('russ', 'Русский язык'),
        ('it', 'Информатика'),
    ]
    subjects = models.CharField(
        max_length=4,
        choices=SUBJECT,
        default='math',
    )
    number = models.IntegerField()
    ave_rating = models.FloatField()

    def __str__(self):
        return str(self.number)



class Ratings(models.Model):
    rating = models.IntegerField()
    user = models.ForeignKey('Users', on_delete=models.CASCADE)
    kabinet = models.ForeignKey('Kabinet', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.kabinet) + "_" + str(self.rating)


class Comments(models.Model):
    coment = models.TextField()
    user = models.ForeignKey('Users', on_delete=models.CASCADE)
    kabinet = models.ForeignKey('Kabinet', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.kabinet) + "_" + str(self.coment[0:10])

mysite/myownsite/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from . import models


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = models.Users
        fields = ("username", "email")

class Comm(forms.ModelForm):

    class Meta:
        model = models.Comments
        fields = ("coment", "kabinet")

mysite/myownsite/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.shortcuts import redirect
from .forms import CustomUserCreationForm
from . import forms
from . import models

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

def comm_new(request):
    if request.method == "POST":
        form = forms.Comm(request.POST)
        post = form.save(commit = False)
        post.user = request.user
        if models.Comments.objects.filter(user = request.user, kabinet = post.kabinet).exists() == 0:
            post.save()
        return redirect('home')
    else:
        form = forms.Comm()
    return render(request, 'new_comm.html', {'form' : form})

def home(request):
    kab = models.Kabinet.objects.all()
    return render(request, 'home.html', {'kab': kab})

def kab_detail(request, pk):
    kab = models.Kabinet.objects.get(pk=pk)
    coments=models.Comments.objects.filter(kabinet=kab)
    return render(request, 'kabinet_detail.html', {'kab': kab, 'coments':coments})

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link href="https://exot1k310.pythonanywhere.com/{% static 'css/myownsite.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Rubik+80s+Fade">
    <img src="C:\Users\kirka\OneDrive\Изображения\a51b172e-9f16-43eb-8be1-fdcdbd175ca8.jpg">
</head>
<body>
  <div class="header">
    <a href="/" class="logo">1502 Внутришкольный интерактивный сайт</a>
    <div class="header-right">
    {% if user.is_authenticated %}
        <a href="{% url 'comm_new' %}">Добавить отзыв</a>
        <a class="active" href="{% url 'logout' %}">Log Out</a>
{% else %}
        <a class="active" href="{% url 'login' %}">Log In</a> |
        <a class="active" href="{% url 'signup' %}">Sign Up</a>
{% endif %}
      </div>
  </div>


  <main>
    {% block content %}
    {% endblock %}
  </main>

<div class="footer">
    </h1> <a  href="https://vk.com/kirka310"> Обратная связь </a> </h1>
</div>
</body>

</html>

mysite/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}

{% for i in kab %}
<h3><a href='{% url 'kab_detail' pk=i.pk %}'>Кабинет {{ i.number }}</a></h3>
<p>{{ i.get_subject_display }}</p>
{% endfor %}
{% endblock %}

mysite/templates/kabinet_detail.html
{% extends 'base.html' %}

{% block content %}
<h5>Кабинет {{ kab.number }}</h5>
<p>{{ kab.get_subjects_display }}</p>
<p>{{ kab.ave_rating }}</p>

{% for i in coments %}
<h5>{{ i.user }}</h5>
<p>{{ i.coment }}</p>
{% endfor %}

{% endblock %}

mysite/templates/new_comm.html
{% extends 'base.html' %}

{% block content %}
<h2>Добавьте новый отзыв к кабинету</h2>
<form method="POST" class = "Comm">
  {% csrf_token %}
  {{ form.as_p }}
<button type = "submit"> Сохранить </button>
</form>
{% endblock %}